suppress -Wmissing-field-initializers warnings when building PHP bindings
SWIG-generated code produces warnings on some platforms:

    CXX      libgv_php_la-gv_php.lo
  gv_php.cpp:5389:1: error: missing initializer for member
    '_zend_function_entry::num_args' [-Werror=missing-field-initializers]
   };
   ^

It is not helpful to be told about problems in third-party code. Suppressing
these will enable us to make -Wmissing-field-initializers fail-on-warning in
future.