fix 'qt' memory leaks
Coverity notes:

  Error: RESOURCE_LEAK (CWE-772): [#def101]
  graphviz-2.40.1/lib/edgepaint/node_distinct_coloring.c:249: alloc_fn: Storage
    is returned from allocation function "lab_gamut_quadtree".
  graphviz-2.40.1/lib/edgepaint/lab.c:256:3: alloc_fn: Storage is returned from
    allocation function "QuadTree_new_from_point_list".
  graphviz-2.40.1/lib/sparse/QuadTree.c:383:3: alloc_fn: Storage is returned
    from allocation function "QuadTree_new".
  graphviz-2.40.1/lib/sparse/QuadTree.c:405:3: alloc_fn: Storage is returned
    from allocation function "gmalloc".
  graphviz-2.40.1/lib/common/memory.c:47:5: alloc_fn: Storage is returned from
    allocation function "malloc". [Note: The source code implementation of the
    function has been overridden by a builtin model.]
  graphviz-2.40.1/lib/common/memory.c:47:5: var_assign: Assigning: "rv" =
    "malloc(nbytes)".
  graphviz-2.40.1/lib/common/memory.c:51:5: return_alloc: Returning allocated
    memory "rv".
  graphviz-2.40.1/lib/sparse/QuadTree.c:405:3: var_assign: Assigning: "q" =
    "gmalloc(80UL)".
  graphviz-2.40.1/lib/sparse/QuadTree.c:418:3: return_alloc: Returning allocated
    memory "q".
  graphviz-2.40.1/lib/sparse/QuadTree.c:383:3: var_assign: Assigning: "qt" =
    "QuadTree_new(dim, center, width, max_level)".
  graphviz-2.40.1/lib/sparse/QuadTree.c:387:7: identity_transfer: Passing "qt"
    as argument 1 to function "QuadTree_add", which returns that argument.
  graphviz-2.40.1/lib/sparse/QuadTree.c:555:11: return_parm: Returning parameter
    "q".
  graphviz-2.40.1/lib/sparse/QuadTree.c:387:7: noescape: Resource "qt" is not
    freed or pointed-to in function "QuadTree_add".
  graphviz-2.40.1/lib/sparse/QuadTree.c:554:32: noescape:
    "QuadTree_add(QuadTree, double *, double, int)" does not free or save its
    parameter "q".
  graphviz-2.40.1/lib/sparse/QuadTree.c:387:7: var_assign: Assigning: "qt" =
    "QuadTree_add(qt, &coord[i * dim], weight[i], i)".
  graphviz-2.40.1/lib/sparse/QuadTree.c:387:7: identity_transfer: Passing "qt"
    as argument 1 to function "QuadTree_add", which returns that argument.
  graphviz-2.40.1/lib/sparse/QuadTree.c:555:11: return_parm: Returning
    parameter "q".
  graphviz-2.40.1/lib/sparse/QuadTree.c:387:7: noescape: Resource "qt" is not
    freed or pointed-to in function "QuadTree_add".
  graphviz-2.40.1/lib/sparse/QuadTree.c:554:32: noescape:
    "QuadTree_add(QuadTree, double *, double, int)" does not free or save its
    parameter "q".
  graphviz-2.40.1/lib/sparse/QuadTree.c:387:7: var_assign: Assigning: "qt" =
    "QuadTree_add(qt, &coord[i * dim], weight[i], i)".
  graphviz-2.40.1/lib/sparse/QuadTree.c:399:3: return_alloc: Returning
    allocated memory "qt".
  graphviz-2.40.1/lib/edgepaint/lab.c:256:3: var_assign: Assigning: "qt" =
    "QuadTree_new_from_point_list(dim, n, max_qtree_level, x, NULL)".
  graphviz-2.40.1/lib/edgepaint/lab.c:260:3: return_alloc: Returning allocated
    memory "qt".
  graphviz-2.40.1/lib/edgepaint/node_distinct_coloring.c:249: var_assign:
    Assigning: "qt" = storage returned from "lab_gamut_quadtree("lab_gamut",
    lightness, max_qtree_level)".
  graphviz-2.40.1/lib/edgepaint/node_distinct_coloring.c:281: leaked_storage:
    Variable "qt" going out of scope leaks the storage it points to.
  #  279|     if (n != A->n) {
  #  280|       *flag = -1;
  #  281|->     return;
  #  282|     }
  #  283|

  Error: RESOURCE_LEAK (CWE-772): [#def102]
  graphviz-2.40.1/lib/edgepaint/node_distinct_coloring.c:292: alloc_arg:
    "SparseMatrix_weakly_connected_components" allocates memory that is stored
    into "comps_ptr".
  graphviz-2.40.1/lib/sparse/SparseMatrix.c:2566:22: alloc_fn: Storage is
    returned from allocation function "gmalloc".
  graphviz-2.40.1/lib/common/memory.c:47:5: alloc_fn: Storage is returned from
    allocation function "malloc". [Note: The source code implementation of the
    function has been overridden by a builtin model.]
  graphviz-2.40.1/lib/common/memory.c:47:5: var_assign: Assigning: "rv" =
    "malloc(nbytes)".
  graphviz-2.40.1/lib/common/memory.c:51:5: return_alloc: Returning allocated
    memory "rv".
  graphviz-2.40.1/lib/sparse/SparseMatrix.c:2566:22: var_assign: Assigning:
    "*comps_ptr" = "gmalloc(4UL * (size_t)(m + 1))".
  graphviz-2.40.1/lib/edgepaint/node_distinct_coloring.c:318: leaked_storage:
    Variable "comps_ptr" going out of scope leaks the storage it points to.
  #  316|
  #  317|     if (A != A0) SparseMatrix_delete(A);
  #  318|-> }

This memory leak seems to have been present ever since this code was introduced
in aadee957012e676c9aaf36ec40cb2860c178e269.

Gitlab: #1464
Reported-by: Jaroslav Škarvada <jskarvad@redhat.com>