Update and adapt to new Windows versions of the GD library and its dependencies
This updates the Windows libraries submodule which contains newly
installed vcpkg versions of the GD library and its dependencies and
adapts the CMake and MSBuild build systems to the new versions. For x86,
the new GD library installed under
windows/dependencies/libraries/vcpkg/installed/x86 is used instead of
the legacy version under windows/dependencies/libraries/x86, while for
x64, we had no legacy version before this.

This makes the GD plugin available also for x64 on native windows and
thus fixes #1787.

It also makes the 'diffimg' utility available for x64 also on native
Windows and thus fixes #1788 also for x64.

It also makes the 'webp' plugin available in the CMake builds on
native Windows.

This also replaces explicit import declarations of some GD font related
symbols with inclusion of the GD header files which declare these
symbols. With explicit import declarations, we got the following error
messages when building the GD plugin statically:

```
gvplugin_gd.lib(gvrender_gd.obj) : error LNK2001: unresolved external symbol gdFontTiny [C:\Users\magjac\graphviz\build\cmd\dot\dot.vcxproj]
gvplugin_gd.lib(gvrender_gd.obj) : error LNK2001: unresolved external symbol gdFontSmall [C:\Users\magjac\graphviz\build\cmd\dot\dot.vcxproj]
gvplugin_gd.lib(gvrender_gd.obj) : error LNK2001: unresolved external symbol gdFontMediumBold [C:\Users\magjac\graphviz\build\cmd\dot\dot.vcxproj]
gvplugin_gd.lib(gvrender_gd.obj) : error LNK2001: unresolved external symbol gdFontLarge [C:\Users\magjac\graphviz\build\cmd\dot\dot.vcxproj]
gvplugin_gd.lib(gvrender_gd.obj) : error LNK2001: unresolved external symbol gdFontGiant [C:\Users\magjac\graphviz\build\cmd\dot\dot.vcxproj]
C:\Users\magjac\graphviz\build\cmd\dot\Debug\dot.exe : fatal error LNK1120: 5 unresolved externals [C:\Users\magjac\graphviz\build\cmd\dot\dot.vcxproj]
```
and without including the new header files, we get:
```
C:\Users\magjac\graphviz\plugin\gd\gvrender_gd.c(280,45): error C2065: 'gdFontTiny': undeclared identifier [C:\Users\magjac\graphviz\build\plugin\gd\gvplugin_gd.vcxproj]
C:\Users\magjac\graphviz\plugin\gd\gvrender_gd.c(282,46): error C2065: 'gdFontSmall': undeclared identifier [C:\Users\magjac\graphviz\build\plugin\gd\gvplugin_gd.vcxproj]
C:\Users\magjac\graphviz\plugin\gd\gvrender_gd.c(284,51): error C2065: 'gdFontMediumBold': undeclared identifier [C:\Users\magjac\graphviz\build\plugin\gd\gvplugin_gd.vcxproj]
C:\Users\magjac\graphviz\plugin\gd\gvrender_gd.c(286,46): error C2065: 'gdFontLarge': undeclared identifier [C:\Users\magjac\graphviz\build\plugin\gd\gvplugin_gd.vcxproj]
C:\Users\magjac\graphviz\plugin\gd\gvrender_gd.c(288,46): error C2065: 'gdFontGiant': undeclared identifier [C:\Users\magjac\graphviz\build\plugin\gd\gvplugin_gd.vcxproj]
```
The legacy x86 libgd doesn't declare these symbols in any header. This
is probably what's described in this 20+ year old thread:
https://comp.graphics.apps.gnuplot.narkive.com/9oiZWQuj/gnuplot-with-libgd-for-windows,
so we cannot make this change before introducing the new vcpkg version
of the GD library.

GitLab: #1786, #1788