sfio: remove unused 'oargs'
The last use of this was removed in 515db14ba4e311145741e1675848131226150a08.
This was being copied around for no purpose. What motivated this investigation
that led to this discovery was a report from Coverity that it was also a
resource leak:

  Error: VARARGS (CWE-237): [#def189]
  graphviz-2.40.1/lib/sfio/sfvscanf.c:135: va_init: Initializing va_list "oargs".
  graphviz-2.40.1/lib/sfio/sfvscanf.c:795: missing_va_end: va_end was not called
    for "oargs".
  #  793|   	n_assign = -1;
  #  794|
  #  795|->     SFMTXRETURN(f, n_assign);
  #  796|   }

Gitlab: #1464, #1998
Reported-by: Jaroslav Škarvada <jskarvad@redhat.com>