tclpathplan: fix read of uninitialized 'p'
The merge of 8b243d3708d5151a6d9075a045fc8dca5d62483e caused compilation of
tclpathplan on macOS with CMake to fail in CI:

  [ 99%] Building C object tclpkg/tclpathplan/CMakeFiles/tclplan.dir/tclpathplan.c.o
  /Users/gitlab/builds/graphviz/graphviz/tclpkg/tclpathplan/tclpathplan.c:782:33:
    error: variable 'p' is uninitialized when used here [-Werror,-Wuninitialized]
                      appendpoint(interp, scale(p, ps[j], gain));
                                                ^
  /Users/gitlab/builds/graphviz/graphviz/tclpkg/tclpathplan/tclpathplan.c:383:5:
    note: variable 'p' is declared here
      point p, q, *ps;
      ^
  1 error generated.

This error message is correct, but this was surprising, as that series was not
intended to alter tclpathplan in a way that could cause something like this.
Inspecting build logs revealed that on the prior main commit
(8d6f53cfb58d8f8775ef136daecc5e365a162f86) tclpathplan.c was not compiled.
Bisecting reveals 521001c982e57cdfe1f23d785c2571fbc5acfcc9 caused this change in
behavior. This seems to have been another silent failure caused by our misuse of
`add_custom_command`.

This bug appears to have existed ever since the first revision of this file.

Gitlab: #2530