sparse SparseMatrix_multiply_dense: remove support for passing in null 'res'
Coverity believes a memory leak occurs in `prolongate` in lib/sparse (see
below). This is because it passes in the address of a local (`y`) to a function
(`SparseMatrix_multiple_dense`) that conditionally allocates heap memory and
stores it to this location. This is a false positive, but only because `y` is
not null in the only call to `prolongate`. Scanning the rest of the code base,
the only other call into `SparseMatrix_multiple_dense` also passes a non-null
pointer. So lets ease the lives of readers and static analysis tools by removing
this conditional path that is unused.

  Error: RESOURCE_LEAK (CWE-772): [#def155]
  graphviz-2.40.1/lib/sfdpgen/spring_electrical.c:1814: alloc_arg:
    "SparseMatrix_multiply_dense" allocates memory that is stored into "y".
  graphviz-2.40.1/lib/sparse/SparseMatrix.c:1208:5: alloc_arg:
    "SparseMatrix_multiply_dense1" allocates memory that is stored into "*res".
  graphviz-2.40.1/lib/sparse/SparseMatrix.c:1132:13: alloc_fn: Storage is
    returned from allocation function "gmalloc".
  graphviz-2.40.1/lib/common/memory.c:47:5: alloc_fn: Storage is returned from
    allocation function "malloc". [Note: The source code implementation of the
    function has been overridden by a builtin model.]
  graphviz-2.40.1/lib/common/memory.c:47:5: var_assign: Assigning:
    "rv" = "malloc(nbytes)".
  graphviz-2.40.1/lib/common/memory.c:51:5: return_alloc: Returning allocated
    memory "rv".
  graphviz-2.40.1/lib/sparse/SparseMatrix.c:1132:13: var_assign: Assigning:
    "u" = "gmalloc(8UL * (size_t)m * (size_t)dim)".
  graphviz-2.40.1/lib/sparse/SparseMatrix.c:1139:25: noescape: Resource "u" is
    not freed or pointed-to in function "dense_transpose".
  graphviz-2.40.1/lib/sparse/SparseMatrix.c:1100:35: noescape:
    "dense_transpose(double *, int, int)" does not free or save its parameter
    "v".
  graphviz-2.40.1/lib/sparse/SparseMatrix.c:1151:3: var_assign: Assigning:
    "*res" = "u".
  graphviz-2.40.1/lib/sfdpgen/spring_electrical.c:1818: noescape: Resource "y"
    is not freed or pointed-to in "interpolate_coord".
  graphviz-2.40.1/lib/sfdpgen/spring_electrical.c:1789:55: noescape:
    "interpolate_coord(int, SparseMatrix, double *)" does not free or save its
    parameter "x".
  graphviz-2.40.1/lib/sfdpgen/spring_electrical.c:1830: leaked_storage:
    Returning without freeing "y" leaks the storage that it points to.
  # 1828|       }
  # 1829|     }
  # 1830|-> }
  # 1831|
  # 1832|

Gitlab: #1464
Reported-by: Jaroslav Škarvada <jskarvad@redhat.com>