dotgen _dot_splines: fix memory leaks
Coverity observes:

  Error: RESOURCE_LEAK (CWE-772): [#def92]
  graphviz-2.40.1/lib/dotgen/dotsplines.c:288: alloc_fn: Storage is returned
    from allocation function "zmalloc".
  graphviz-2.40.1/lib/common/memory.c:25:5: alloc_fn: Storage is returned from
    allocation function "gmalloc".
  graphviz-2.40.1/lib/common/memory.c:47:5: alloc_fn: Storage is returned from
    allocation function "malloc". [Note: The source code implementation of the
    function has been overridden by a builtin model.]
  graphviz-2.40.1/lib/common/memory.c:47:5: var_assign: Assigning: "rv" =
    "malloc(nbytes)".
  graphviz-2.40.1/lib/common/memory.c:51:5: return_alloc: Returning allocated
    memory "rv".
  graphviz-2.40.1/lib/common/memory.c:25:5: var_assign: Assigning: "rv" =
    "gmalloc(nbytes)".
  graphviz-2.40.1/lib/common/memory.c:26:5: noescape: Resource "rv" is not freed
    or pointed-to in function "memset". [Note: The source code implementation of
    the function has been overridden by a builtin model.]
  graphviz-2.40.1/lib/common/memory.c:27:5: return_alloc: Returning allocated
    memory "rv".
  graphviz-2.40.1/lib/dotgen/dotsplines.c:288: var_assign: Assigning: "P" =
    storage returned from "zmalloc(120UL)".
  graphviz-2.40.1/lib/dotgen/dotsplines.c:513: leaked_storage: Variable "P"
    going out of scope leaks the storage it points to.
  #  511|       State = GVSPLINES;
  #  512|       EdgeLabelsDone = 1;
  #  513|-> }
  #  514|
  #  515|   /* dot_splines:

  Error: RESOURCE_LEAK (CWE-772): [#def93]
  graphviz-2.40.1/lib/dotgen/dotsplines.c:292: alloc_fn: Storage is returned
    from allocation function "zmalloc".
  graphviz-2.40.1/lib/common/memory.c:25:5: alloc_fn: Storage is returned from
    allocation function "gmalloc".
  graphviz-2.40.1/lib/common/memory.c:47:5: alloc_fn: Storage is returned from
    allocation function "malloc". [Note: The source code implementation of the
    function has been overridden by a builtin model.]
  graphviz-2.40.1/lib/common/memory.c:47:5: var_assign: Assigning: "rv" =
    "malloc(nbytes)".
  graphviz-2.40.1/lib/common/memory.c:51:5: return_alloc: Returning allocated
    memory "rv".
  graphviz-2.40.1/lib/common/memory.c:25:5: var_assign: Assigning: "rv" =
    "gmalloc(nbytes)".
  graphviz-2.40.1/lib/common/memory.c:26:5: noescape: Resource "rv" is not freed
    or pointed-to in function "memset". [Note: The source code implementation of
    the function has been overridden by a builtin model.]
  graphviz-2.40.1/lib/common/memory.c:27:5: return_alloc: Returning allocated
    memory "rv".
  graphviz-2.40.1/lib/dotgen/dotsplines.c:292: var_assign: Assigning: "edges" =
    storage returned from "zmalloc(1024UL)".
  graphviz-2.40.1/lib/dotgen/dotsplines.c:363: noescape: Resource
    "(char *)&edges[0]" is not freed or pointed-to in "qsort".
  graphviz-2.40.1/lib/dotgen/dotsplines.c:513: leaked_storage: Variable "edges"
    going out of scope leaks the storage it points to.
  #  511|       State = GVSPLINES;
  #  512|       EdgeLabelsDone = 1;
  #  513|-> }
  #  514|
  #  515|   /* dot_splines:

At first these look like false positives or something that has been fixed since
the Coverity scan was run. But observe that the allocations of these variables
are unconditional while their deallocation was conditional.

Gitlab: #1464
Reported-by: Jaroslav Škarvada <jskarvad@redhat.com>