common: add declaration of drand48 to utils.h when the system doesn't have it
This function is implemented in utils.c when not available otherwise.

Removes this warning with MinGW:

C:/Users/magja/graphviz/lib/fdpgen/tlayout.c:597:33: warning: implicit declaration of function 'drand48'; did you mean 'srand48'? [-Wimplicit-function-declaration]
  597 |       double angle = PItimes2 * drand48();
      |                                 ^~~~~~~
      |                                 srand48