neatogen power_iteration_orthog: remove unused 'iteration'
Clang in macOS 13 gains the ability to spot this:

  /Users/gitlab/builds/graphviz/graphviz/lib/neatogen/smart_ini_x.c:80:6: error: variable 'iteration' set but not used [-Werror,-Wunused-but-set-variable]
          int iteration;
              ^