CI: do not install libglade on macOS
Glade is unavailable on an M1 Mac:

  +++ brew install libglade
  Error: libglade has been disabled because it is not maintained upstream!
  +++ brew upgrade libglade
  Error: libglade not installed

Glade also seems unavailable on “Sonoma (arm64)” on MacPorts.¹ So this may be
the end of the road for Smyrna on macOS.

Gitlab: #2411, #2422

¹ https://ports.macports.org/port/libglade2/details/