gv2gxl writeNondefaultAttr: remove unused 'cnt'
Clang in macOS 13 gains the ability to spot this:

  /Users/gitlab/builds/graphviz/graphviz/cmd/tools/gv2gxl.c:509:9: error: variable 'cnt' set but not used [-Werror,-Wunused-but-set-variable]
      int cnt = 0;
          ^