gvedit: switch from default C++14 to C++17
This is second and final step to avoid error messages like:

C:\Users\magjac\graphviz\windows\dependencies\libraries\vcpkg\installed\x86-windows\include\Qt6\QtCore\qcompilerdetection.h(1220,1): fatal error C1189: #error:  "Qt requires a C++17 compiler, and a suitable value for __cplusplus. On MSVC, you must pass the /Zc:__cplusplus option to the compiler."