tclpkg: fix 'ictx' memory leak
Coverity says:

  Error: CPPCHECK_WARNING (CWE-401): [#def240]
  graphviz-2.40.1/tclpkg/tcldot/tcldot.c:183: error[memleak]: Memory leak: ictx
  #  181|   #ifdef USE_TCL_STUBS
  #  182|       if (Tcl_InitStubs(interp, TCL_VERSION, 0) == NULL) {
  #  183|-> 	return TCL_ERROR;
  #  184|       }
  #  185|   #else

  Error: CPPCHECK_WARNING (CWE-401): [#def241]
  graphviz-2.40.1/tclpkg/tcldot/tcldot.c:191: error[memleak]: Memory leak: ictx
  #  189|   #endif
  #  190|       if (Tcl_PkgProvide(interp, "Tcldot", PACKAGE_VERSION) != TCL_OK) {
  #  191|-> 	return TCL_ERROR;
  #  192|       }
  #  193|

`ictx` is heap allocated, so one of these command registrations needs to also
indicate it needs to eventually be freed. We arbitrarily choose the first
command and assume that only the entire interpreter will be torn down at once,
not individual commands.

Gitlab: #1464
Reported-by: Jaroslav Škarvada <jskarvad@redhat.com>