GDI+ plugin gdiplus_gen_beginpage: fix: avoid using 'image' uninitialized
When building this plugin using the CMake build system in release mode, the
compiler notes:

  In member function '__ct ',
      inlined from '__ct_comp ' at C:/GitLab-Runner/builds/smattr/graphviz/plugin/gdiplus/gvrender_gdiplus.cpp:35:56,
      inlined from 'gdiplusgen_begin_page' at C:/GitLab-Runner/builds/smattr/graphviz/plugin/gdiplus/gvrender_gdiplus.cpp:124:50:
  C:/msys64/mingw64/include/gdiplus/gdiplusgraphics.h:66:69: error: 'image' may be used uninitialized [-Werror=maybe-uninitialized]
     66 |                 lastStatus = DllExports::GdipGetImageGraphicsContext(
        |                                                                     ^
  C:/GitLab-Runner/builds/smattr/graphviz/plugin/gdiplus/gvrender_gdiplus.cpp: In function 'gdiplusgen_begin_page':
  C:/GitLab-Runner/builds/smattr/graphviz/plugin/gdiplus/gvrender_gdiplus.cpp:101:24: note: 'image' was declared here
    101 |                 Image *image;
        |                        ^

This appears to be a true positive, indicating an actual bug. Backtracking this,
it was introduced in commit eff48627602c397f6dcab79627bdfa01a733eb5d. It is
quite hard to spot this bug with manual inspection due to the chaotic
indentation style in this source file.