fix macOS compilation of htmlparse.c
For unknown reasons, the series merged in
e8f2d1dfeb0268535e0875b8efe9e67a1be607a4 causes a change to the parser code seen
on macOS resulting in a warning that causes compilation failure in CI:

  [ 20%] Building C object lib/common/CMakeFiles/common_obj.dir/htmlparse.c.o
  /Users/gitlab/builds/graphviz/graphviz/build/lib/common/htmlparse.c:1108:9: error: variable 'htmlnerrs' set but not used [-Werror,-Wunused-but-set-variable]
      int yynerrs = 0;
          ^
  /Users/gitlab/builds/graphviz/graphviz/build/lib/common/htmlparse.c:73:25: note: expanded from macro 'yynerrs'
  #define yynerrs         htmlnerrs
                          ^