tcldot tcldot_layout: rewrite to use public libgvc API
This code was calling private functions of libgvc. Surprisingly the only
platform to rigorously enforce this separation seems to be MinGW where
compilation fails:

  C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/14.1.0/../../../../i686-w64-mingw32/bin/ld.exe: tclpkg/tcldot/CMakeFiles/tcldot.dir/tcldot-util.c.obj:tcldot-util.c:(.text+0x9c8): undefined reference to `gvlayout_select'
  C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/14.1.0/../../../../i686-w64-mingw32/bin/ld.exe: tclpkg/tcldot/CMakeFiles/tcldot.dir/tcldot-util.c.obj:tcldot-util.c:(.text+0x9e3): undefined reference to `gvlayout_select'
  C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/14.1.0/../../../../i686-w64-mingw32/bin/ld.exe: tclpkg/tcldot/CMakeFiles/tcldot.dir/tcldot-util.c.obj:tcldot-util.c:(.text+0xa2c): undefined reference to `gvlayout_select'
  C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/14.1.0/../../../../i686-w64-mingw32/bin/ld.exe: tclpkg/tcldot/CMakeFiles/tcldot.dir/tcldot-util.c.obj:tcldot-util.c:(.text+0xa43): undefined reference to `gvlayout_select'
  C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/14.1.0/../../../../i686-w64-mingw32/bin/ld.exe: tclpkg/tcldot/CMakeFiles/tcldot.dir/tcldot-util.c.obj:tcldot-util.c:(.text+0xa62): undefined reference to `gvlayout_select'

51401f001686d7f53ab465174fbe2570c232c551 implemented near identical logic to
this inside libgvc, so we can do an almost 1-1 replacement by replacing all of
this with a call to the public API.

Gitlab: #2530, #2546